---
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    
---
<style>

body {
  padding-top:0px;
  background-color:white;
}

.navbar{
  visibility: hidden
}

</style>

```{r setup, include=FALSE}

library(flexdashboard)
library(readxl)
library (readr)
library(dplyr)
Population <- read_csv("Sites/SITE1/_files/Population.csv")
dave1="https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv"
dave1<-read_csv(url(dave1))
dave1<-inner_join(Population, dave1, by = c("State1" = "state"))
MA<-subset(dave1, State=="MA")
MA$DailyNewPOS <- (MA$cases-lag(MA$cases))
MA$DailyNewDeath <- (MA$deaths-lag(MA$deaths))

```

Column {data-width=200}
-----------------------------------------------------------------------

### Chart A

```{r}

valueBox(subset(MA,date==Sys.Date()-1)$DailyNewPOS, "Yesterdays New Cases","fa fa-medkit")

```

Column {data-width=200}
-----------------------------------------------------------------------

### Chart B

```{r}

valueBox(subset(MA,date==Sys.Date()-1)$DailyNewDeath, "Yesterdays New Deaths","fa fa-medkit")

```


Column {data-width=200}
-----------------------------------------------------------------------

### Chart C

```{r}

valueBox(subset(MA,date==Sys.Date()-1)$DailyNewDeath)

```

Column {data-width=200}
-----------------------------------------------------------------------

### Chart D

```{r}

valueBox(42, caption = "Errors", icon="fa-thumbs-down")

```

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>
